### ISSUE TITLE
History retrieve returned status code 400

### ISSUE THREAD

**Issue by zjpleau** [rubasace/radarr-custom-format-sync#10]
First off, thank you coming up with this tool! I lost all of my AMZN/NF custom profiles a while back and didn't think I'd ever be able to recover them. 

I ran the docker container but immediately got this error:
`2020-12-04 11:35:32,870 [MainThread  ] [INFO ]  CustomFormatSync Version 1.0.0
2020-12-04 11:35:39,209 [MainThread  ] [ERROR]  History retrieve returned status code 400
{'message': 'BadRequest: Invalid sort key movie.title', 'content': 'Invalid sort key movie.title'}`

I'm thinking this may be because I am running radarr v3 but I didn't see anything about version requirements.  Thanks!

**Comment by rubasace** [comment]
Hi @zjpleau. I'm gald to read my tool has helped you :)

I'm afraid it's not compatible with v3 yet. I'll update the docs to reflect it.

**Comment by rubasace** [comment]
Hi again @zjpleau . I've been looking at updating the script to make it v3 compatible. But I just realized I don't need it anymore as v3 has fixed the issues with audio detection that caused the initial issue. 
Could you maybe explain your use case?
